====== DEPLOYMENT STARTED ======
>>> Pulling latest code from master branch...
Already up to date.
>>> Installing NPM dependencies...
... (npm ka output) ...
>>> Restarting application with PM2...
[PM2] Applying action restartProcessId on app [irapp-be](ids: 0)
[PM2] [irapp-be](0) ✓
====== DEPLOYMENT COMPLETED SUCCESSFULLY ======
